id: I8084178C
ocr_import_info:
  timestamp: '2023-07-26T13:04:02.034459+00:00'
  batch_id: batch-ed79
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/stable
  ocr_lang_hint: bo
  software_id: ocr-pipelines@v0.1.11
  sponsor: DS
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-26 13:09:37.595798+00:00
last_modified: 2023-07-26 13:09:37.595806+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9413
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9413
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷོའི་ཆོས་འབྱུང་བསྟན་པ་རིན་པོ་ཆེའི་འཕྲོ་མཐུད་འཇམ་དགོན་སྨོན་མཐའི་འཕྲེང་བ།
  languages:
  - bo
  author: འབྲུག་རྗེ་མཁན་པོ ༡༠་བསྟན་འཛིན་ཆོས་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.365473389810546
  ocr_word_median_confidence_index: 0.31983417000000003
bases:
  I1KG9466:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9466
      total_pages: 312
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9466.txt
    statistics:
      ocr_word_median_confidence_index: 0.31983417000000003
      ocr_word_mean_confidence_index: 0.365473389810546
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
